# Use root/example as user/password credentials
version: '3'
services:
  covid-mysql:
    container_name: covid-mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: midas
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  covid-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: covid-app
    ports:
      - 8080:8080
    depends_on:
      - covid-mysql
    links:
      - "covid-mysql:database"